name: Deployment Workflow

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Minikube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Deploy PostgreSQL
        run: kubectl apply -f ../../db-deployment.yaml

      - name: Deploy devops-demo:v2
        run: kubectl apply -f ../../backend-deployment.yaml

      - name: Deploy react-image:v2
        run: kubectl apply -f ../../frontend-deployment.yaml
