name: CI

on:
  workflow_dispatch: # Manually trigger workflow runs
  push:
    branches: [main] # Trigger the workflow on push to the master/main branch

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest # Run on Ubuntu using the latest version

    steps:
      - name: Check-out your repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Tests
        run: mvn -B test
