name: CI Pipeline (DOC1)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: My First Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Check-out your repository
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Continuous Integration"
